language: ruby
cache: bundler
rvm: 2.0.0

notifications:
  email:
    on_success: never
    on_failure: always

install:
  - bundle install
  - curl -O https://raw.githubusercontent.com/wireapp/wire-ios-shared-resources/master/Dangerfile

script:
  - bundle exec danger
