language: objective-c
osx_image: xcode7.3

install:
  - carthage bootstrap --platform iOS

script:
  - open -b com.apple.iphonesimulator
  - set -o pipefail
  - xcodebuild build test -scheme ZMCMockTransport -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.3' | xcpretty -s
